name: CI Pipeline

on:
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - '[skip ci]'

jobs:
  fetch-repository:
    uses: ./.github/workflows/reusable_checkout.yml

  run-lint:
    needs: fetch-repository
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Run lint
        run: |
          python -m black --check .
  
  run-tests:
    needs: fetch-repository
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.8]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          python -m pytest .
